In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from astropy.io import ascii

In [2]:
it = 0

raw_dir = "/Users/z5114326/Documents/GitHub/GC_kinematics/data/result/m12i/raw/it_%d/" % it
main_out = "allcat_s-%d_p2-7_p3-1.txt" % it
disrupt = "allcat_s-%d_p2-7_p3-1_k-1.5_logm_snap596.txt" % it
gc_id = "allcat_s-%d_p2-7_p3-1_gcid.txt" % it

In [3]:
with open(raw_dir + main_out) as f:
    content = f.readlines()

dat = ascii.read(content)

dat["col1"].name = "halo(z=0)"
dat["col2"].name = "logMh(z=0)"
dat["col3"].name = "logM*(z=0)"
dat["col4"].name = "logMh(zfrom)"
dat["col5"].name = "logM*(zform)"
dat["col6"].name = "LogM(tform)"
dat["col7"].name = "zform"
dat["col8"].name = "feh"
dat["col9"].name = "isMPB"
dat["col10"].name = "halo(zform)"
dat["col11"].name = "snapnum(zform)"

main_df = dat.to_pandas()

In [4]:
dis = pd.read_csv(raw_dir + disrupt, header=None)
dis.columns = ["log(M_gc)"]

In [5]:
gcid = pd.read_csv(raw_dir + gc_id, sep=" ").drop(["ID"], axis=1)
gcid.columns = ["GC_ID", "quality"]

In [6]:
len(dis[dis["log(M_gc)"] != -1])

225

In [7]:
comb_df = pd.concat([main_df, dis, gcid], axis=1, join="inner")
comb_df

halo(z=0)  logMh(z=0)  logM*(z=0)  logMh(zfrom)  logM*(zform)  \
0       25236877      12.065       10.95         8.316         4.196   
1       25236877      12.065       10.95         8.356         4.243   
2       25236877      12.065       10.95         8.501         4.437   
3       25236877      12.065       10.95         8.654         4.574   
4       25236877      12.065       10.95         8.799         4.789   
...          ...         ...         ...           ...           ...   
12825   25236877      12.065       10.95         9.205         5.146   
12826   25236877      12.065       10.95         9.205         5.146   
12827   25236877      12.065       10.95         9.227         5.196   
12828   25236877      12.065       10.95         8.316         4.394   
12829   25236877      12.065       10.95         8.492         4.440   

       LogM(tform)  zform    feh  isMPB  halo(zform)  snapnum(zform)  \
0            4.029  9.154 -2.999      1        41048              21   
1            4.437  9.000 -2.977      1        44992              22   
2            4.124  8.545 -2.897      1        58441              25   
3            4.179  7.727 -2.814      1        92024              31   
4            4.201  7.348 -2.728      1       111792              34   
...            ...    ...    ...    ...          ...             ...   
12825        4.521  2.319 -2.151      0      2985513             148   
12826        4.013  2.319 -2.151      0      2985513             148   
12827        4.057  2.284 -2.136      0      3076292             150   
12828        4.031  8.692 -2.597      0        55049              24   
12829        4.000  6.333 -2.409      0       195125              44   

       log(M_gc)      GC_ID  quality  
0           -1.0  119998556        0  
1           -1.0  119998556        0  
2           -1.0  120188656        0  
3           -1.0   51358838        2  
4           -1.0  122241197        0  
...          ...        ...      ...  
12825       -1.0   87810505        0  
12826       -1.0   87968184        0  
12827       -1.0   87810505        0  
12828       -1.0  101879042        0  
12829       -1.0  103617694        0  

[12830 rows x 14 columns]

In [30]:
np.min(comb_df[(comb_df["log(M_gc)"] != -1)]["snapnum(zform)"])

36

In [43]:
comb_df[(comb_df["quality"] == 2) & (comb_df["log(M_gc)"] != -1)]

halo(z=0)  logMh(z=0)  logM*(z=0)  logMh(zfrom)  logM*(zform)  \
193     25236877      12.065       10.95        10.500         7.619   
198     25236877      12.065       10.95        10.500         7.619   
199     25236877      12.065       10.95        10.500         7.619   
240     25236877      12.065       10.95        10.581         7.771   
255     25236877      12.065       10.95        10.581         7.771   
...          ...         ...         ...           ...           ...   
12544   25236877      12.065       10.95        10.691         8.034   
12548   25236877      12.065       10.95        10.691         8.034   
12554   25236877      12.065       10.95        10.703         8.059   
12557   25236877      12.065       10.95        10.703         8.059   
12567   25236877      12.065       10.95        10.703         8.059   

       LogM(tform)  zform    feh  isMPB  halo(zform)  snapnum(zform)  \
193          5.820  4.040 -1.634      1       791663              83   
198          5.394  4.040 -1.634      1       791663              83   
199          5.421  4.040 -1.634      1       791663              83   
240          5.518  4.000 -1.584      1       813599              84   
255          5.272  4.000 -1.584      1       813599              84   
...            ...    ...    ...    ...          ...             ...   
12544        5.352  1.423 -1.134      0      6760235             218   
12548        5.280  1.423 -1.134      0      6760235             218   
12554        5.355  1.414 -1.123      0      6819141             219   
12557        5.056  1.414 -1.123      0      6819141             219   
12567        5.289  1.414 -1.123      0      6819141             219   

       log(M_gc)     GC_ID  quality  
193        5.321  63047079        2  
198        3.623  56746921        2  
199        4.355  63531841        2  
240        4.797  57550735        2  
255        4.262  62674731        2  
...          ...       ...      ...  
12544      4.830  62461942        2  
12548      4.711  61809534        2  
12554      4.872  61394861        2  
12557      3.970  50660546        2  
12567      4.462  40083387        2  

[185 rows x 14 columns]

In [8]:
top = np.array(comb_df[comb_df["log(M_gc)"] != -1]["GC_ID"])

In [9]:
values, counts = np.unique(top, return_counts=True)
counts

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [10]:
funk = np.array(comb_df[comb_df["log(M_gc)"] != -1]["quality"])
funk

array([2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 1, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 0, 2, 2, 2, 0, 0, 1, 2, 2, 2,
       2, 2, 2, 2, 1, 0, 0, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2])

In [11]:
snapform = np.array(comb_df[comb_df["log(M_gc)"] != -1]["snapnum(zform)"])
new = set(snapform)
new = np.array(list(new)) + 4
np.sort(new)

array([ 40,  67,  68,  71,  72,  73,  74,  76,  77,  82,  83,  84,  85,
        87,  88,  89,  90,  92,  94,  95,  96,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 111, 114, 116, 119, 120, 121, 123, 124,
       125, 128, 129, 130, 131, 132, 135, 146, 147, 149, 150, 151, 152,
       154, 155, 157, 158, 175, 176, 189, 209, 210, 211, 212, 213, 222,
       223, 238, 239, 240, 241])