In [1]:
import gizmo_analysis as gizmo
import h5py
import halo_analysis as halo
import numpy as np

In [74]:
halo_file = "/Users/z5114326/Documents/GitHub/GC_kinematics/data/base_halo/halo_25236877.hdf5"
tree_file = "/Users/z5114326/Documents/GitHub/GC_kinematics/data/base_tree/merger_tree_25236877.hdf5"
simulation_directory = "/Volumes/My Passport for Mac/m12i_res7100"

In [75]:
GC_ID = 119998556
offset = 4
hal_form = 44992
yt_formsnap = 22
formsnap = yt_formsnap + offset

In [3]:
test_dir = "/Volumes/My Passport for Mac/m12i_res7100/halo/rockstar_dm/catalog_hdf5/halo_083.hdf5"

pop = h5py.File(test_dir)

In [ ]:
pop.keys()

In [76]:
f_halo = h5py.File(halo_file)
f_tree = h5py.File(tree_file)

hal = halo.io.IO.read_catalogs("index", formsnap, simulation_directory, species="star")
halt = halo.io.IO.read_tree(simulation_directory=simulation_directory)


# in utilities.simulation.Snapshot():
* reading:  Volumes/My Passport for Mac/m12i_res7100/snapshot_times.txt

  using snapshot index = 26, redshift = 9.000



* read 749 halos from:  Volumes/My Passport for Mac/m12i_res7100/halo/rockstar_dm/catalog_hdf5/halo_026.hdf5

# in halo_analysis.halo_io.Particle():
* read 749 halos, 134 have star particles, from:  Volumes/My Passport for Mac/m12i_res7100/halo/rockstar_dm/catalog_hdf5/star_026.hdf5
* assigning primary host and coordinates wrt it to halo catalog...  finished


# in utilities.simulation.Snapshot():
* reading:  Volumes/My Passport for Mac/m12i_res7100/snapshot_times.txt

* read 17859038 halos from:  Volumes/My Passport for Mac/m12i_res7100/halo/rockstar_dm/catalog_hdf5/tree.hdf5



In [77]:
for pop in f_halo["snap_22_halo_44992"]["dm"]["ParticleIDs"]:
    if pop == 119998556:
        print(pop)

119998556


In [78]:
for key in f_halo.keys():
    print(key)

snap_116_halo_1708217
snap_116_halo_1708294
snap_116_halo_1708322
snap_116_halo_1708442
snap_116_halo_1708605
snap_116_halo_1708679
snap_116_halo_1708773
snap_116_halo_1708821
snap_116_halo_1708888
snap_116_halo_1708896
snap_116_halo_1708947
snap_116_halo_1708955
snap_116_halo_1708957
snap_116_halo_1708975
snap_116_halo_1709006
snap_116_halo_1709011
snap_116_halo_1709080
snap_116_halo_1709107
snap_116_halo_1709173
snap_116_halo_1709176
snap_116_halo_1709213
snap_116_halo_1709216
snap_116_halo_1709269
snap_116_halo_1709281
snap_116_halo_1709288
snap_116_halo_1709331
snap_116_halo_1709354
snap_116_halo_1709396
snap_116_halo_1709403
snap_116_halo_1709472
snap_116_halo_1709495
snap_116_halo_1709543
snap_116_halo_1709601
snap_116_halo_1709722
snap_116_halo_1709790
snap_116_halo_1709985
snap_116_halo_1710003
snap_116_halo_1710141
snap_116_halo_1710262
snap_116_halo_1710341
snap_116_halo_1710348
snap_116_halo_1710366
snap_116_halo_1710440
snap_116_halo_1710549
snap_116_halo_1710593
snap_116_h

In [79]:
for key in f_tree.keys():
    print(key)

DescendantID
FirstProgenitorID
J
MainLeafProgenitorID
NextProgenitorID
ScaleRad
SnapNum
SubfindID
SubhaloID
SubhaloMass
SubhaloPos
SubhaloVel


In [80]:
halo_id_lst = np.array([halo_id for halo_id in f_tree["SubfindID"]])

In [81]:
halo_idx = np.where(halo_id_lst == hal_form)[0][0]

In [125]:
mass = f_tree["SubhaloMass"][halo_idx]
snap = f_tree["SnapNum"][halo_idx]
main_prog = f_tree["FirstProgenitorID"][halo_idx]
pos = f_tree["SubhaloPos"][halo_idx]

In [108]:
halo_idx

2157553

In [158]:
Ob = 0.0455
Om = 0.272

fb = Ob / Om  # baryon fraction to correct for halo mass

In [159]:
6 / 2 / 3 * 2 * 3

6.0

In [174]:
mass_corr = mass * 1e10 * (1 - fb)
mass_corr

132800000.0

In [171]:
np.where(halt["snapshot"] == formsnap)[0][0]

2157553

In [173]:
halt["mass.vir"][2157553]

195014240.0

In [154]:
halt["mass"][halo_idx] / 1e10 / (1 - fb)

0.022720979242384105

In [180]:
cat_idx = halt["catalog.index"][halo_idx]
hal["mass.vir"][cat_idx]

195014240.0

In [130]:
f_halo["snap_22_halo_44992"]["dm"].keys()

<KeysViewHDF5 ['Coordinates', 'Masses', 'ParticleIDs', 'Potential', 'Velocities']>

In [132]:
yt_pid_lst = np.array([pid for pid in f_halo["snap_22_halo_44992"]["dm"]["ParticleIDs"]])

In [135]:
pid_idx = np.where(yt_pid_lst == GC_ID)[0][0]

In [138]:
f_halo["snap_22_halo_44992"]["dm"]["Coordinates"][pid_idx]

array([30656.56140804, 29236.41942277, 31015.75274273])

In [141]:
np.max(f_tree["SubhaloMass"])

81.46790286975717

In [140]:
hal["position"]

array([[41979.86 , 42236.81 , 43524.348],
       [41982.54 , 42259.73 , 43544.46 ],
       [42263.86 , 41845.543, 43738.293],
       ...,
       [45083.734, 44332.81 , 43405.44 ],
       [43805.785, 44082.34 , 44676.81 ],
       [43303.223, 45004.402, 43410.37 ]], dtype=float32)

In [196]:
test = np.round(halt["mass.vir"] / 1e10 / (1 - fb), 4)

array([1.085242e+02, 1.085037e+02, 1.700000e-03, ..., 0.000000e+00,
       0.000000e+00, 0.000000e+00], dtype=float32)

In [208]:
test_list = np.where(test == np.round(mass, 4))

In [213]:
np.where(halt["snapshot"][test_list] == 26)[0]

array([112, 295])

In [221]:
test_list[0][112], test_list[0][295]

(2157751, 3861728)