In [2]:
import gizmo_analysis as gizmo
import halo_analysis as halo
import matplotlib.pyplot as plt
import numpy as np
import utilities as ut
from gc_utils import get_halo_tree, main_prog_halt  # noqa: F401
from scipy.optimize import minimize, minimize_scalar

In [3]:
sim = "m12i"
snapshot = 600

sim_dir = "../../../simulations/"
# sim_dir = "../../simulations/"
data_dir = "data/"
sim_codes = data_dir + "external/simulation_codes.json"

fire_dir = sim_dir + sim + "/" + sim + "_res7100/"

In [4]:
halt = get_halo_tree(sim, sim_dir)

Retrieving Halo Tree.....................: 100%|████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.20s/it]


In [51]:
snap_lst = np.linspace(10, 600, 591, dtype=int)
# hals = halo.io.IO.read_catalogs("index", 600, fire_dir, species="star", assign_hosts_rotation=True)
hals = halo.io.IO.read_catalogs("index", 600, fire_dir, species="star")

In [50]:
part = gizmo.io.Read.read_snapshots("all", "index", 600, fire_dir)

In [17]:
halt["catalog.index"][0]

27728

In [52]:
halt.keys()

dict_keys(['am.phantom', 'am.progenitor.main', 'axis.b/a', 'axis.c/a', 'catalog.index', 'central.index', 'central.local.index', 'descendant.index', 'descendant.snapshot', 'dindex', 'final.index', 'host.distance', 'host.index', 'host.velocity', 'host.velocity.rad', 'host.velocity.tan', 'major.merger.snapshot', 'mass', 'mass.180m', 'mass.200c', 'mass.200m', 'mass.500c', 'mass.bound', 'mass.lowres', 'mass.vir', 'position', 'position.offset', 'progenitor.co.dindex', 'progenitor.co.index', 'progenitor.last.dindex', 'progenitor.main.index', 'progenitor.main.last.dindex', 'progenitor.number', 'radius', 'scale.radius', 'scale.radius.klypin', 'snapshot', 'spin.bullock', 'spin.peebles', 'tid', 'vel.circ.max', 'vel.std', 'velocity', 'velocity.offset'])

In [54]:
halt["position"][0], halt["velocity"][0]

(array([41792.168, 44131.21 , 46267.684], dtype=float32),
 array([-53.27,  72.65,  95.25], dtype=float32))

In [62]:
new_rot = ut.particle.get_principal_axes(
    part,
    species_name="star",
    center_positions=halt["position"][0],
    center_velocities=halt["velocity"][0],
)

In [63]:
new_rot.keys()

dict_keys(['rotation', 'axis.ratios'])

In [64]:
SpeciesProfile = ut.particle.SpeciesProfileClass(limits=[0, 336], width=336 / 2)
pro = SpeciesProfile.get_sum_profiles(
    part, "all", "mass", center_position=halt["position"][0], rotation=new_rot["rotation"]
)

/Users/z5114326/Documents/GitHub/gc_kinematics/.venv/lib/python3.12/site-packages/utilities/binning.py:832: RuntimeWarning: invalid value encountered in divide
  pro['density.norm'] = pro['sum'] / self.volume_fracs / np.sum(pro['sum'])
/Users/z5114326/Documents/GitHub/gc_kinematics/.venv/lib/python3.12/site-packages/utilities/binning.py:840: RuntimeWarning: invalid value encountered in divide
  pro['fraction'] = pro['sum'] / np.sum(pro['sum'])
/Users/z5114326/Documents/GitHub/gc_kinematics/.venv/lib/python3.12/site-packages/utilities/binning.py:842: RuntimeWarning: invalid value encountered in divide
  pro['fraction.cum'] = pro['sum.cum'] / pro['sum.cum'].max()


In [65]:
np.sum(pro["total"]["sum"])

1180536922112.0

In [66]:
hals["star.radius.90"][27728]

9.09705

In [55]:
part.host.keys()

dict_keys(['position', 'velocity', 'acceleration', 'rotation', 'axis.ratios'])

In [57]:
part.host["position"]

array([[41792.15 , 44131.234, 46267.68 ]], dtype=float32)

In [68]:
hals.prop("baryon.mass")

KeyError: 'not sure how to parse property = baryon.mass'

In [69]:
halt.prop("progenitor.indices", 0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36], dtype=int32)